### ISSUE TITLE
Static app route, not written to custom cache during build

### ISSUE THREAD

**Issue by Urogna** [caching-tools/next-shared-cache#369] opened 2024-02-27 19:08 UTC
When building a nextjs app (with app router), some routes can have static body and metadata.
When using version 1.0.3 of the cache-handler, these static routes are not stored in the custom cache.

**Severity**
Minor

**Frequency of Occurrence**
Always

**Steps to Reproduce**
1. Create new next app, add `@neshca/cache-handler` custom cache handler as per documentation.
2. Add new app/static/route.ts file with content
```
export async function GET() {
  return new Response('OK', { status: 200 });
}
```
3. build the app

**Expected vs. Actual Behavior**
`/static` route is saved into cache during build and not when first browsing the route manually

**Environment:**
- OS: [Windows, Linux]
- Node.js version: [e.g., 20.9.0]
- `@neshca/cache-handler` version: [1.0.3]
- `next` version: [14.1.0]

**Attempted Solutions or Workarounds**
Describe any attempted solutions or workarounds and their outcomes.

**Impact of the Bug**
Some of our routes have some info only during build time, and not when the app is actually deployed

**Comment by better-salmon** [comment] 2024-02-28 09:28
Hey @Urogna! I've tested it and figured out that it is not a bug. By default, Next.js puts into the cache only fetch results during the build. However, CacheHandler does not read from the file system, which causes static routes to run during runtime.

While this behavior is not a bug, I am considering implementing a feature that will cache static routes and pages after the build.

Let's close this issue and open a new one with a feature request.

**Comment by Urogna** [comment] 2024-02-28 10:06
@better-salmon thanks for the quick response and looking into it. I suspected that had something to do with the nextjs cache handler api.
While playing around with the basic setup, I found another bug with probably higher severity.
The first time a route response gets cached, it returns base64 string instead of the decoded response, but on subsequent requests it returns it correctly (picture 1 vs picture 2), picture 3 shows the saved cache in redis
![image](https://github.com/caching-tools/next-shared-cache/assets/32796629/d757724e-e5f5-4746-8f58-0b311739fcbf)
![image](https://github.com/caching-tools/next-shared-cache/assets/32796629/39dc8c05-c7ea-452c-b3d2-7ef0fd84124a)
![image](https://github.com/caching-tools/next-shared-cache/assets/32796629/8b706725-8721-4c09-9ccb-052dcec6acf6)

Should I open a new issue for this, or is this enough here?

**Comment by better-salmon** [comment] 2024-02-28 10:10
I have fixed this bug in #373, which is included in [release 1.0.4](https://github.com/caching-tools/next-shared-cache/releases/tag/%40neshca%2Fcache-handler%401.0.4).

**Comment by Urogna** [comment] 2024-02-28 10:17
About the feature request... Static pages/routes, are not necessarily needed in the custom cache, since when deploying on multiple pods/instances, the static pages are deployed as well, and are present on all instances... So if there's a way to fallback to file system for static routs/pages then the problem would be fixed, not sure if it's easily implemented though. Just a thought.

**Comment by better-salmon** [comment] 2024-02-28 10:20
Thanks for opening this issue! Now, I'm closing it as won't fix.

Let's discuss feature request in the discussions section.

**Closed as not planned by better-salmon** 2024-02-28 10:20 UTC
Labels: bug
